FROM ubuntu:14.04
MAINTAINER Liu Siyuan <SLIU019@e.ntu.edu.sg>

RUN apt-get update && apt-get install -y wget
RUN wget http://repo.continuum.io/archive/Anaconda2-4.0.0-Linux-x86_64.sh
RUN bash Anaconda2-4.0.0-Linux-x86_64.sh
RUN rm Anaconda2-4.0.0-Linux-x86_64.sh
